export const SEESAW_TOGGLE = 'SEESAW_TOGGLE';
export const SEESAW_ENDED = 'SEESAW_ENDED';
export const SEESAW_MOVE_RIGHT = 'SEESAW_MOVE_RIGHT';
export const SEESAW_MOVE_LEFT = 'SEESAW_MOVE_LEFT';
export const SEESAW_RESET = 'SEESAW_RESET';
export const SEESAW_INSERT_RIGHT_ELEMENT = 'SEESAW_INSERT_RIGHT_ELEMENT';
export const SEESAW_INSERT_LEFT_ELEMENT = 'SEESAW_INSERT_LEFT_ELEMENT';
export const SEESAW_FALL_ENDED = 'SEESAW_FALL_ENDED';
export const SEESAW_INSERT_FALLING_ELEMENT = 'SEESAW_INSERT_FALLING_ELEMENT';
export const SEESAW_INITIALIZE_FALLING_ELEMENTS =
	'SEESAW_INITIALIZE_FALLING_ELEMENTS';
